#!/usr/bin/env php
<?php

define('ROOT', __DIR__ . '/');

require_once ROOT . 'vendor/autoload.php';

use Ermarian\EjabberdAuth\EjabberdAuth;

try {
  EjabberdAuth::createFromFile(ROOT . 'config.yml')->run();
}
catch (\Exception $exception) {
  file_put_contents('php://stderr', $exception->getMessage() . "\n");
}
