<?php

function phpbb30_init($config) {
  global $phpbb_root_path;
  $phpbb_root_path = $config['root_path'];
  // Bootstrap the phpBB system.
  require_once __DIR__ . '/phpbb30_bootstrap.php';
  // Load the plugin.
  require_once __DIR__ . '/BridgePhpBB30.php';
  return new BridgePhpBB30($auth, $db);
}

function phpbb30_session($config) {
  global $phpbb_root_path;
  $phpbb_root_path = $config['root_path'];
  // Bootstrap the phpBB system.
  require_once __DIR__ . '/phpbb30_bootstrap.php';
  $GLOBALS['user'] = new user();
  $GLOBALS['user']->session_begin();
  return !empty($GLOBALS['user']->data['username']) ?
         $GLOBALS['user']->data['username'] : FALSE;
}
