<?php

function htpasswd_init($config) {
  $data = array();
  $file = $config['htpasswd_file'];
  if (file_exists($file) && is_readable($file)) {
    $lines = explode("\n", trim(file_get_contents($file)));
    foreach ($lines as $line) {
      list($user, $password) = explode(":", trim($line), 2);
      $data[$user] = $password;
    }
  }

  // Load the plugin.
  require_once __DIR__ . '/BridgeHtpasswd.php';
  require_once __DIR__ . '/htpasswd.inc';
  return new BridgeHtpasswd($data, $config);
}
