<?php

use Drupal\Core\DrupalKernel;

function drupal7_init($config) {
  define('DRUPAL_ROOT', $config['root_path']);
  $_SERVER['REMOTE_ADDR'] = '127.0.0.1';
  require_once DRUPAL_ROOT . '/includes/bootstrap.inc';
  //require_once DRUPAL_ROOT . '/core/includes/common.inc';
  require_once __DIR__ . '/BridgeDrupal7.php';
  drupal_static('conf_path', "sites/{$config['site']}");
  drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);
  return new BridgeDrupal7();
}